import type { StreamEvent } from "./types";

/**
 * GENERATED by eval/bake.ts — do not edit by hand.
 *
 * Real event logs captured from live runs of the tribunal. Replaying these gives
 * a genuine trial instantly and deterministically: no API calls, no rate limit,
 * no slow retrieval while a judge is watching. Every verdict, source and
 * argument below was produced by the real pipeline.
 */

export type Fixture = {
  id: string;
  label: string;
  blurb: string;
  text: string;
  events: StreamEvent[];
};

export const FIXTURES: Fixture[] = [
  {
    "id": "fabrication",
    "label": "The killer — a fabricated citation",
    "blurb": "An AI answer that invents a study and distorts a real one.",
    "text": "Remote work is now clearly better for output. A 2019 Stanford study found that remote workers are 43% more productive than office workers, and a 2021 Harvard Medical School paper concluded that three cups of coffee daily reverses liver fibrosis.",
    "events": [
      {
        "type": "claims",
        "claims": [
          {
            "id": "c1",
            "text": "A 2019 Stanford study found that remote workers are 43% more productive than office workers",
            "status": "pending",
            "verdict": null,
            "confidence": null,
            "failureType": null,
            "reasoning": null,
            "disagreement": null,
            "sources": [],
            "arguments": []
          },
          {
            "id": "c2",
            "text": "A 2021 Harvard Medical School paper concluded that three cups of coffee daily reverses liver fibrosis",
            "status": "pending",
            "verdict": null,
            "confidence": null,
            "failureType": null,
            "reasoning": null,
            "disagreement": null,
            "sources": [],
            "arguments": []
          }
        ]
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "retrieving"
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s1",
          "url": "https://compt.io/blog/is-remote-working-more-productive-statistics-and-real-experiences",
          "domain": "compt.io",
          "title": "Is Remote Working More Productive?",
          "snippet": "The best I can surmise here is that whereas employees used to stretch this work to fill more of their workday when in office, they are now incentivized to quickly knock these tasks out so they can leave their computer and focus on personal matters. For example, they know a certain task pre-COVID was expected to take 3 ",
          "stance": "neutral",
          "credibility": 0.7
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s2",
          "url": "https://www.linkedin.com/posts/isharad_stanford-university-says-remote-work-kills-activity-7379116674244870145-VcAO",
          "domain": "linkedin.com",
          "title": "Stanford University says remote work kills productivity. | Sharad Verma",
          "snippet": "Most people think remote work looks like this: 🍺 🐕 🧘♀️ 📺 🏝️ (They're dead wrong) This successful post with 10k likes is from CA member Stephen Baines 🔥 Original post below: ⬇️ ⬇️ ⬇️ Most people think remote work looks like this: 🍺 🐕 🧘♀️ 📺 🏝️ (They're dead wrong) It's not... 📺 Netflix on in the background 🧺",
          "stance": "neutral",
          "credibility": 0.69
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s3",
          "url": "https://www.apollotechnical.com/working-from-home-productivity-statistics",
          "domain": "apollotechnical.com",
          "title": "51 Surprising Working From Home Productivity Statistics",
          "snippet": "Reports from surveys taken show working from home is producing a better turnaround on projects, and increasing productivity. A survey by Stanford found that only 65% of Americans had internet fast enough to handle video calls. With 42% of Americans working from home and 26% working at their employer’s physical location",
          "stance": "neutral",
          "credibility": 0.69
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s4",
          "url": "https://emailanalytics.com/does-working-from-home-increase-productivity",
          "domain": "emailanalytics.com",
          "title": "Does Working from Home Increase Productivity? (2026) - Email Analytics",
          "snippet": "Communication Efficiency: Effectiveness of information exchange between remote team members. Output-Based Metrics: Performance measurements focused on completed work rather than time spent. Talent Pool Expansion: Increased candidate options when geographic hiring limitations are removed. ## Frequently Asked Questions #",
          "stance": "neutral",
          "credibility": 0.67
        }
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "arguing"
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-source_quality",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "source quality",
          "position": "None of the provided sources contain a 2019 Stanford study reporting that remote workers are 43% more productive than office workers; the claim is not supported by the evidence base.",
          "sourceIds": [
            "c1-s1",
            "c1-s2",
            "c1-s3",
            "c1-s4"
          ],
          "strength": 0.2
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-temporal",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "temporal staleness",
          "position": "The claim cites a 2019 Stanford study reporting a 43% productivity boost for remote workers, yet none of the provided sources are that study nor do they mention the 43% figure; they are later articles (e.g., a 2026 piece) that discuss remote work productivity without supporting the specific statistic, indicating the claim is unsupported and likely outdated.",
          "sourceIds": [
            "c1-s1",
            "c1-s4"
          ],
          "strength": 0.6
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-entity",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "entity conflation",
          "position": "No source shows a 2019 Stanford study reporting remote workers are 43% more productive; the Stanford references cited either discuss general productivity perceptions (c1-s1) or unrelated surveys without that figure (c1-s3), indicating the claim conflates entities and misattributes a finding.",
          "sourceIds": [
            "c1-s1",
            "c1-s3"
          ],
          "strength": 0.6
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-logic",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "logical leap",
          "position": "None of the provided sources substantiate a Stanford study reporting remote workers are 43% more productive; the cited articles either omit any such statistic or discuss unrelated topics, so the claim extrapolates without evidence.",
          "sourceIds": [
            "c1-s1",
            "c1-s3"
          ],
          "strength": 0.8
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-defense",
          "claimId": "c1",
          "role": "defense",
          "lens": "strongest defense",
          "position": "No provided source confirms a 2019 Stanford study reporting remote workers are 43% more productive than office workers; the available references either discuss unrelated aspects or lack the specific statistic.",
          "sourceIds": [],
          "strength": 0
        }
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "judging"
      },
      {
        "type": "verdict",
        "claimId": "c1",
        "verdict": "refuted",
        "confidence": 0.91,
        "failureType": "fabricated_citation",
        "reasoning": "None of the retrieved sources identifies a 2019 Stanford study finding that remote workers were 43% more productive than office workers. The Stanford-related source c1-s3 discusses internet access and workforce location but provides neither the claimed study nor the 43% figure, so the citation cannot be substantiated as described.",
        "disagreement": 0.44
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "retrieving"
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s1",
          "url": "https://www.michiganmedicine.org/health-lab/can-drinking-coffee-lead-healthier-liver",
          "domain": "michiganmedicine.org",
          "title": "Can drinking coffee lead to a healthier liver?",
          "snippet": "### The results The team found that individuals who consumed more than three cups of coffee a day showed reduced levels of liver stiffness when lifestyle factors were considered. They also found that these same individuals experienced reduced risks associated with increased liver stiffness. \"While coffee consumption wa",
          "stance": "neutral",
          "credibility": 0.67
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s2",
          "url": "https://www.webmd.com/fatty-liver-disease/coffee-help-liver",
          "domain": "webmd.com",
          "title": "Can Coffee Help Your Liver Fight Disease?",
          "snippet": "## Fighting Disease If you already have a problem with your liver, coffee may help with that. Research shows that moderate amounts, typically between 1 and 3 cups a day, may slow down the following conditions: ## How It Helps In addition to caffeine, coffee has more than 1,000 chemicals. Doctors are still trying to fig",
          "stance": "neutral",
          "credibility": 0.62
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s3",
          "url": "https://media.neliti.com/media/publications/69693-ID-none.pdf",
          "domain": "media.neliti.com",
          "title": "Coffee Consumption to Reduce Liver Fibrosis - Neliti",
          "snippet": "As one of the most popular drink consumed daily, coffee is known to be good for health. One of the main substance found in coffee is caffeine. Several previous studies explained that caffeine found in coffee could act as hepatoprotective agents, and recently an antifibrotic agent. Since liver fibrosis is a fatal condit",
          "stance": "neutral",
          "credibility": 0.59
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s4",
          "url": "https://www.cghjournal.org/article/S1542-3565(21)01057-0/fulltext",
          "domain": "cghjournal.org",
          "title": "Coffee Consumption Is Associated With Lower Liver Stiffness: A Nationally Representative Study - Clinical Gastroenterology and Hepatology",
          "snippet": "In our study, we found that more than 3 cups of coffee daily were associated with reduced liver stiffness, accounting for lifestyle confounders. People who drink more than 3 cups experienced a reduced risk associated with increased liver stiffness of 9.5 kPa or more (OR, 0.4; 95% CI, 0.2–1.0). Adjusting for consumption",
          "stance": "neutral",
          "credibility": 0.59
        }
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "arguing"
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-source_quality",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "source quality",
          "position": "No source provided is a 2021 Harvard Medical School paper; the cited articles are secondary health sites and a journal summary that only report an association between >3 cups of coffee and reduced liver stiffness, not a reversal of fibrosis, and none are authored by Harvard researchers.",
          "sourceIds": [
            "c2-s1",
            "c2-s2",
            "c2-s3",
            "c2-s4"
          ],
          "strength": 0.8
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-temporal",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "temporal staleness",
          "position": "No provided source confirms a 2021 Harvard Medical School paper that claims three cups of coffee daily reverses liver fibrosis; the cited articles only report an association with reduced liver stiffness and do not reference such a study, making the claim temporally unsupported.",
          "sourceIds": [
            "c2-s1"
          ],
          "strength": 0.7
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-entity",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "entity conflation",
          "position": "The claim falsely attributes the finding to a 2021 Harvard Medical School paper; the cited evidence comes from other sources (e.g., a Clinical Gastroenterology and Hepatology study and a Michigan Medicine article) and does not mention Harvard or a 2021 paper, indicating an entity conflation.",
          "sourceIds": [
            "c2-s1",
            "c2-s4"
          ],
          "strength": 0.8
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-logic",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "logical leap",
          "position": "The cited sources only report an association between drinking >3 cups of coffee and lower liver stiffness or reduced risk, not that coffee reverses liver fibrosis, nor do they cite a 2021 Harvard Medical School paper making that claim.",
          "sourceIds": [
            "c2-s1",
            "c2-s4"
          ],
          "strength": 0.7
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-defense",
          "claimId": "c2",
          "role": "defense",
          "lens": "strongest defense",
          "position": "The available sources only report that consuming more than three cups of coffee per day is associated with reduced liver stiffness, not that a 2021 Harvard Medical School study concluded coffee reverses liver fibrosis; thus the claim is not directly supported by the evidence.",
          "sourceIds": [
            "c2-s1",
            "c2-s4"
          ],
          "strength": 0.2
        }
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "judging"
      },
      {
        "type": "verdict",
        "claimId": "c2",
        "verdict": "refuted",
        "confidence": 0.96,
        "failureType": "misattribution",
        "reasoning": "The decisive Clinical Gastroenterology and Hepatology source reports only an association between drinking more than three cups daily and lower liver stiffness; it does not conclude that coffee reverses liver fibrosis. None of the evidence substantiates the alleged 2021 Harvard Medical School paper, so the claim both misattributes the research and exaggerates its finding.",
        "disagreement": 0.1
      },
      {
        "type": "done",
        "trustScore": 3
      }
    ]
  },
  {
    "id": "clean",
    "label": "A clean answer",
    "blurb": "Mostly true — proof the tribunal isn't just a cynic.",
    "text": "Honey does not spoil because its low water content and acidity prevent microbial growth. Light takes about eight minutes to travel from the Sun to the Earth, and octopuses have three hearts.",
    "events": [
      {
        "type": "claims",
        "claims": [
          {
            "id": "c1",
            "text": "Honey does not spoil because its low water content and acidity prevent microbial growth",
            "status": "pending",
            "verdict": null,
            "confidence": null,
            "failureType": null,
            "reasoning": null,
            "disagreement": null,
            "sources": [],
            "arguments": []
          },
          {
            "id": "c2",
            "text": "Light takes about eight minutes to travel from the Sun to the Earth",
            "status": "pending",
            "verdict": null,
            "confidence": null,
            "failureType": null,
            "reasoning": null,
            "disagreement": null,
            "sources": [],
            "arguments": []
          },
          {
            "id": "c3",
            "text": "Octopuses have three hearts",
            "status": "pending",
            "verdict": null,
            "confidence": null,
            "failureType": null,
            "reasoning": null,
            "disagreement": null,
            "sources": [],
            "arguments": []
          }
        ]
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "retrieving"
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s1",
          "url": "https://aravalihoney.com/the-chemistry-of-honey-why-it-never-spoils",
          "domain": "aravalihoney.com",
          "title": "The Chemistry of Honey: Why It Never Spoils",
          "snippet": "This makes honey one of the most naturally preserved foods in the world. Its stability is not due to artificial preservatives but a result of complex biological and chemical processes. By choosing pure and responsibly sourced honey from trusted brands like Aravalihoney, consumers can enjoy not only its taste but also i",
          "stance": "neutral",
          "credibility": 0.82
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s2",
          "url": "https://www.amesfarm.com/blogs/honey/why-honey-doesnt-spoil-the-science-explained",
          "domain": "amesfarm.com",
          "title": "Why Honey Doesn't Spoil (The Science Explained)",
          "snippet": "Once the nectar is stored in honeycomb cells, bees use their wings to circulate air throughout the hive. This process gradually evaporates excess moisture from the nectar until it reaches the ideal consistency and water content. After the honey is sufficiently concentrated, bees seal the honeycomb cells with beeswax ca",
          "stance": "neutral",
          "credibility": 0.81
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s3",
          "url": "https://www.smileyhoney.com/blogs/honey-school/honeys-natural-preservation",
          "domain": "smileyhoney.com",
          "title": "Why Honey Never Spoils: The Science Behind Its Natural Preservation",
          "snippet": "Table of content ## [TL;DR] Honey stands as nature's most remarkable preservative, capable of lasting thousands of years without spoiling. This ancient sweetener combines multiple preservation mechanisms including high sugar concentration (80%), low water content (15-18%), acidic pH (3-4.5), and unique enzymes that pro",
          "stance": "neutral",
          "credibility": 0.8
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s4",
          "url": "https://goodfriendhoney.com/journal/the-antimicrobial-properties-of-honey.html",
          "domain": "goodfriendhoney.com",
          "title": "The Antimicrobial Properties of Honey | The Hive Journal",
          "snippet": "Low water activity and acidity work together. There is also an enzymatic component. When bees convert nectar into honey, they introduce an enzyme called glucose oxidase. In the presence of small amounts of moisture, this enzyme can produce low levels of hydrogen peroxide. Not in concentrations that damage healthy tissu",
          "stance": "neutral",
          "credibility": 0.74
        }
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "arguing"
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-source_quality",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "source quality",
          "position": "The sources are commercial honey‑producer webpages that merely repeat common marketing claims about low water content, acidity and enzymes, without citing peer‑reviewed studies or direct evidence that these factors alone prevent microbial growth; thus the claim is not substantiated by reliable sources.",
          "sourceIds": [
            "c1-s3",
            "c1-s4"
          ],
          "strength": 0.35
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-temporal",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "temporal staleness",
          "position": "No argument returned.",
          "sourceIds": [],
          "strength": 0.5
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-entity",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "entity conflation",
          "position": "The claim does not conflate distinct entities; it simply attributes honey’s resistance to spoilage to low water content and acidity, which aligns with the sources, though they also note additional factors like enzymes, but no mis‑attribution of identity occurs.",
          "sourceIds": [
            "c1-s3",
            "c1-s4"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-logic",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "logical leap",
          "position": "No argument returned.",
          "sourceIds": [],
          "strength": 0.5
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-defense",
          "claimId": "c1",
          "role": "defense",
          "lens": "strongest defense",
          "position": "Honey’s low water activity (about 15‑18%) and its acidic pH (around 3‑4.5) together inhibit microbial growth, which is why honey does not spoil.",
          "sourceIds": [
            "c1-s3",
            "c1-s4"
          ],
          "strength": 0.85
        }
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "judging"
      },
      {
        "type": "verdict",
        "claimId": "c1",
        "verdict": "supported",
        "confidence": 0.88,
        "failureType": "none",
        "reasoning": "The evidence supports the established explanation that honey’s low water availability and acidic pH inhibit the microorganisms responsible for ordinary spoilage. Smiley Honey gives the relevant water-content and pH ranges, while Goodfriend Honey explicitly says low water activity and acidity work together; additional enzymatic protection complements rather than contradicts the claim.",
        "disagreement": 0.33
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "retrieving"
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s1",
          "url": "https://spacedaily.com/d-light-takes-about-8-minutes-to-travel-from-the-sun-to-the-earth-but-the-energy-carried-in-that-sunlight-was-generated-in-the-suns-core-tens-to-hundreds-of-thousands-of-years-ago-bouncing-t",
          "domain": "spacedaily.com",
          "title": "Light takes about 8 minutes to travel from the sun to the Earth, but the energy carried in that sunlight was generated in the sun's core ten",
          "snippet": "Sunlight takes about eight minutes and twenty seconds to travel from the Sun to the Earth. That figure is well-known and accurate. The slightly less well-known part of the story is what happens before the eight-minute trip. The energy carried in any photon of sunlight currently reaching the Earth was generated by nucle",
          "stance": "neutral",
          "credibility": 0.87
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s2",
          "url": "https://www.youtube.com/watch?v=Yer_9es33oE",
          "domain": "youtube.com",
          "title": "How long does it take light to travel from the sun to earth",
          "snippet": "# How long does it take light to travel from the sun to earth ## Know The Science 5600 subscribers 14 likes ### Description 2064 views Posted: 5 Nov 2024 #earthandsundistance Light from the Sun takes about 8 minutes and 20 seconds to reach Earth due to the vast distance between the two, which is roughly 149.6 million k",
          "stance": "neutral",
          "credibility": 0.85
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s3",
          "url": "https://astronomy.stackexchange.com/questions/48941/it-takes-light-roughly-8-minutes-to-travel-to-earth-from-the-sun-but-based-on-w",
          "domain": "astronomy.stackexchange.com",
          "title": "speed - It takes light roughly 8 minutes to travel to Earth from the Sun, but based on which perspective? - Astronomy Stack Exchange",
          "snippet": "Add a comment | 2 $\\begingroup$ To measure the time light takes to travel, we run into an obstacle: if the observer is on Earth, they can not actually measure the point of time at which the photon is emitted from the Sun. Conversely, if the observer is the Sun (let's assume they have a magical spacesuit that protects t",
          "stance": "neutral",
          "credibility": 0.85
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s4",
          "url": "https://www.skyatnightmagazine.com/space-science/how-take-light-from-sun-reach-earth",
          "domain": "skyatnightmagazine.com",
          "title": "How long it takes light from the Sun to reach Earth | BBC Sky at Night Magazine",
          "snippet": "That’ll give you a journey time of some 500 seconds, or eight minutes 20 seconds. Find out how long it takes to walk round the Moon and how long to travel around the world. When we bask in sunlight, it's taken that light 8 minutes 20 seconds to travel to our planet from the centre of the Solar System. Credit: Peter Cad",
          "stance": "neutral",
          "credibility": 0.84
        }
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "arguing"
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-source_quality",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "source quality",
          "position": "The provided sources all directly address the claim and correctly state the ~8‑minute light‑travel time; there is no evidence of misquotation, fabricated citations, or irrelevant sources.",
          "sourceIds": [
            "c2-s1",
            "c2-s2",
            "c2-s3",
            "c2-s4"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-temporal",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "temporal staleness",
          "position": "The claim describes a constant physical relationship that is not subject to temporal staleness, as the speed of light and average Earth-Sun distance remain consistent and the provided sources confirm the figure remains accurate today.",
          "sourceIds": [
            "c2-s1",
            "c2-s2",
            "c2-s4"
          ],
          "strength": 0
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-entity",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "entity conflation",
          "position": "The claim correctly states the approximate light‑travel time from the Sun to Earth; sources distinguish the 8‑minute‑20‑second travel from the Sun’s surface, not from the core, so there is no conflation of distinct entities.",
          "sourceIds": [
            "c2-s1",
            "c2-s2",
            "c2-s4"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-logic",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "logical leap",
          "position": "The claim is a direct factual statement supported by the sources, which give the travel time as about eight minutes (more precisely ~8 min 20 s); there is no logical leap or unwarranted inference.",
          "sourceIds": [
            "c2-s1"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-defense",
          "claimId": "c2",
          "role": "defense",
          "lens": "strongest defense",
          "position": "Light takes roughly eight minutes (about 8 min 20 s) to travel from the Sun to Earth.",
          "sourceIds": [
            "c2-s1",
            "c2-s4"
          ],
          "strength": 0.9
        }
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "judging"
      },
      {
        "type": "verdict",
        "claimId": "c2",
        "verdict": "supported",
        "confidence": 0.99,
        "failureType": "none",
        "reasoning": "The evidence directly confirms that sunlight takes about 8 minutes 20 seconds to reach Earth, making “about eight minutes” an accurate approximation. SpaceDaily and BBC Sky at Night both explicitly substantiate the claim.",
        "disagreement": 0.09
      },
      {
        "type": "claim_status",
        "claimId": "c3",
        "status": "retrieving"
      },
      {
        "type": "source",
        "claimId": "c3",
        "source": {
          "id": "c3-s1",
          "url": "https://study.com/academy/lesson/the-octopus-circulatory-system.html",
          "domain": "study.com",
          "title": "Octopus | Circulatory System, Hearts & Brains - Lesson | Study.com",
          "snippet": "Octopuses have three hearts. Two of the hearts are used to deliver blood to gills while the third is used to deliver blood to other parts of the body. The blood of the octopus is blue because they have copper instead of iron. Copper is more efficient than iron in transporting oxygen to the body at low temperatures. ###",
          "stance": "neutral",
          "credibility": 0.85
        }
      },
      {
        "type": "source",
        "claimId": "c3",
        "source": {
          "id": "c3-s2",
          "url": "https://www.youtube.com/watch?v=0rQy5_TShqM&vl=en-US",
          "domain": "youtube.com",
          "title": "Why Octopuses Have Three Hearts (And Why One Isn’t Enough)",
          "snippet": "If you were designing an animal from scratch, you probably wouldn't give it three hearts. One seems complicated enough. Yet, the octopus, one of the ocean's strangest [music] and smartest creatures, does exactly that. Three hearts, blue blood, arms that think for themselves, and a nervous system unlike almost anything ",
          "stance": "neutral",
          "credibility": 0.85
        }
      },
      {
        "type": "source",
        "claimId": "c3",
        "source": {
          "id": "c3-s3",
          "url": "https://octonation.com/how-many-hearts-does-an-octopus-have",
          "domain": "octonation.com",
          "title": "How Many Hearts Does an Octopus Have? (The Third One Does Something Wild)",
          "snippet": "OctoNation Octopus with textured skin and large eyes in a vibrant reef setting. # How Many Hearts Does an Octopus Have? Octopuses have three hearts: two branchial hearts that pump blood through the gills, and one systemic heart that circulates oxygenated blood throughout the body. But here’s the wild part, that systemi",
          "stance": "neutral",
          "credibility": 0.85
        }
      },
      {
        "type": "source",
        "claimId": "c3",
        "source": {
          "id": "c3-s4",
          "url": "https://www.nwf.org/Educational-Resources/Wildlife-Guide/Invertebrates/Octopuses",
          "domain": "nwf.org",
          "title": "Octopus",
          "snippet": "Octopuses have three functioning hearts. Two of the hearts work exclusively to move blood to the gills, while the third pumps blood through the rest of the body. Rather than iron-based blood, their blood is copper-based, which is more efficient at transporting oxygen at low temperatures and makes their blood blue in co",
          "stance": "neutral",
          "credibility": 0.85
        }
      },
      {
        "type": "claim_status",
        "claimId": "c3",
        "status": "arguing"
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-source_quality",
          "claimId": "c3",
          "role": "prosecutor",
          "lens": "source quality",
          "position": "The cited sources are low‑credibility secondary or popular sources that merely repeat the claim; they do not provide primary or scholarly evidence, but there is no sign of fabricated citations, so the claim is not disproven by source‑quality issues.",
          "sourceIds": [
            "c3-s1",
            "c3-s2",
            "c3-s3",
            "c3-s4"
          ],
          "strength": 0.2
        }
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-temporal",
          "claimId": "c3",
          "role": "prosecutor",
          "lens": "temporal staleness",
          "position": "The claim is a timeless biological fact; none of the sources rely on outdated dates, so there is no temporal staleness issue.",
          "sourceIds": [],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-entity",
          "claimId": "c3",
          "role": "prosecutor",
          "lens": "entity conflation",
          "position": "The claim correctly states that octopuses have three hearts; the sources all refer to the same species and do not conflate different entities.",
          "sourceIds": [
            "c3-s1"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-logic",
          "claimId": "c3",
          "role": "prosecutor",
          "lens": "logical leap",
          "position": "The claim is a straightforward factual statement directly supported by the sources; there is no inference or logical leap involved.",
          "sourceIds": [
            "c3-s1"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-defense",
          "claimId": "c3",
          "role": "defense",
          "lens": "strongest defense",
          "position": "Octopuses possess three hearts: two branchial hearts that pump blood to the gills and a systemic heart that circulates oxygenated blood to the rest of the body.",
          "sourceIds": [
            "c3-s1",
            "c3-s3",
            "c3-s4"
          ],
          "strength": 0.95
        }
      },
      {
        "type": "claim_status",
        "claimId": "c3",
        "status": "judging"
      },
      {
        "type": "verdict",
        "claimId": "c3",
        "verdict": "supported",
        "confidence": 0.99,
        "failureType": "none",
        "reasoning": "Multiple independent sources directly confirm that octopuses have three hearts. The National Wildlife Federation explains that two pump blood to the gills while the third pumps it through the rest of the body, substantiating the claim.",
        "disagreement": 0.09
      },
      {
        "type": "done",
        "trustScore": 98
      }
    ]
  },
  {
    "id": "mixed",
    "label": "A mixed answer",
    "blurb": "True, stale, and mythical claims side by side.",
    "text": "Bananas are slightly radioactive because they contain potassium-40. Pluto is the ninth planet in our solar system. Humans only use 10% of their brains.",
    "events": [
      {
        "type": "claims",
        "claims": [
          {
            "id": "c1",
            "text": "Bananas contain potassium-40",
            "status": "pending",
            "verdict": null,
            "confidence": null,
            "failureType": null,
            "reasoning": null,
            "disagreement": null,
            "sources": [],
            "arguments": []
          },
          {
            "id": "c2",
            "text": "Pluto is the ninth planet in our solar system",
            "status": "pending",
            "verdict": null,
            "confidence": null,
            "failureType": null,
            "reasoning": null,
            "disagreement": null,
            "sources": [],
            "arguments": []
          },
          {
            "id": "c3",
            "text": "Humans only use 10% of their brains",
            "status": "pending",
            "verdict": null,
            "confidence": null,
            "failureType": null,
            "reasoning": null,
            "disagreement": null,
            "sources": [],
            "arguments": []
          }
        ]
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "retrieving"
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s1",
          "url": "https://spacedaily.com/d-bananas-are-slightly-radioactive-they-contain-potassium-40-a-naturally-occurring-radioactive-isotope-and-the-radiation-dose-from-eating-one-banana-is-so-consistently-measurable-that-nuclea",
          "domain": "spacedaily.com",
          "title": "Bananas are slightly radioactive — they contain potassium-40 ...",
          "snippet": "Published Bananas are slightly radioactive — they contain potassium-40, a naturally occurring radioactive isotope, and the radiation dose from eating one banana is so consistently measurable that nuclear scientists use it as an informal unit of measurement, called the Bananas are slightly radioactive. [...] Space, scie",
          "stance": "neutral",
          "credibility": 0.84
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s2",
          "url": "https://en.wikipedia.org/wiki/Banana_equivalent_dose",
          "domain": "en.wikipedia.org",
          "title": "Banana equivalent dose",
          "snippet": "Banana equivalent dose (BED) is an informal unit of measurement of ionizing radiation exposure, intended as a general educational example to compare a dose of radioactivity to the dose one is exposed to by eating one average-sized banana. Bananas contain naturally occurring radioactive isotopes, particularly potassium-",
          "stance": "neutral",
          "credibility": 0.82
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s3",
          "url": "https://assets.ctfassets.net/pc40tpn1u6ef/file-20878/3807ca033f10df6b562ac05ae6b82aaf/16949-catalyst_22_3_516.pdf",
          "domain": "assets.ctfassets.net",
          "title": "about radioactivity",
          "snippet": "22 Catalyst February 2012 Going bananas Bananas are radioactive. They contain potassium-40, a radioactive isotope that emits beta and gamma radiation. If you eat one banana a day, your annual exposure to radiation will increase by about 0.035 millisieverts (mSv). Other radioactive foodstuffs: kidney beans, brazil nuts,",
          "stance": "neutral",
          "credibility": 0.81
        }
      },
      {
        "type": "source",
        "claimId": "c1",
        "source": {
          "id": "c1-s4",
          "url": "https://www.ccnr.org/About_Radioactive_Bananas.pdf",
          "domain": "ccnr.org",
          "title": "About Radioactive Bananas",
          "snippet": "(K-40, 0.012% of total potassium). The much more abundant non-radioactive varieties of potassium found in the body are potassium-39 (K-39, 93% of total K) and potassium-41 (K-41, 7% of total K). These percentages are the same the whole world over, they never change. Every tiny bit of naturally occurring potassium has t",
          "stance": "neutral",
          "credibility": 0.79
        }
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "arguing"
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-source_quality",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "source quality",
          "position": "All provided sources directly state that bananas contain the naturally occurring radioactive isotope potassium‑40, and the citations are real and relevant to the claim",
          "sourceIds": [
            "c1-s1"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-temporal",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "temporal staleness",
          "position": "The claim that bananas contain potassium‑40 is a stable scientific fact; the cited sources, though some are older, describe a constant natural isotopic composition that does not change over time, so there is no temporal staleness issue.",
          "sourceIds": [
            "c1-s1",
            "c1-s2",
            "c1-s3",
            "c1-s4"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-entity",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "entity conflation",
          "position": "No entity conflation is present; multiple sources confirm that bananas indeed contain the radioactive isotope potassium‑40.",
          "sourceIds": [
            "c1-s1"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-logic",
          "claimId": "c1",
          "role": "prosecutor",
          "lens": "logical leap",
          "position": "The claim is a straightforward factual statement directly supported by the sources; there is no inference or logical leap to challenge.",
          "sourceIds": [
            "c1-s1"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c1",
        "argument": {
          "id": "c1-defense",
          "claimId": "c1",
          "role": "defense",
          "lens": "strongest defense",
          "position": "Bananas contain the naturally occurring radioactive isotope potassium‑40, a trace component of potassium that makes the fruit slightly radioactive.",
          "sourceIds": [
            "c1-s1",
            "c1-s2",
            "c1-s3",
            "c1-s4"
          ],
          "strength": 0.95
        }
      },
      {
        "type": "claim_status",
        "claimId": "c1",
        "status": "judging"
      },
      {
        "type": "verdict",
        "claimId": "c1",
        "verdict": "supported",
        "confidence": 0.99,
        "failureType": "none",
        "reasoning": "Multiple sources directly state that bananas contain potassium-40, a naturally occurring radioactive isotope. The Catalyst source and SpaceDaily explicitly confirm the claim, while the CCNR source explains that potassium-40 occurs as a trace fraction of natural potassium.",
        "disagreement": 0
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "retrieving"
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s1",
          "url": "https://www.nationalgeographic.com/science/article/pluto-planet-dwarf-planetoid-solar-system",
          "domain": "nationalgeographic.com",
          "title": "Did Pluto ever actually stop being a planet? Experts debate.",
          "snippet": "ByEric Alt Published February 16, 2024 After its discovery in 1930, Pluto was declared the ninth planet in our solar system and quickly garnered attention not typically afforded to its galactic peers. This was thanks in part to the power of celebrity. The small, multicolored, icy rock has long been associated with Mick",
          "stance": "neutral",
          "credibility": 0.84
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s2",
          "url": "https://science.nasa.gov/dwarf-planets/pluto",
          "domain": "science.nasa.gov",
          "title": "Pluto",
          "snippet": "article 5 months ago # Pluto Pluto was once our solar system's ninth planet, but has been reclassified as a dwarf planet. It's located in the Kuiper Belt. ## Pluto Facts Pluto is a dwarf planet located in a distant region of our solar system beyond Neptune known as the Kuiper Belt. Pluto was long considered our ninth p",
          "stance": "neutral",
          "credibility": 1
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s3",
          "url": "https://en.wikipedia.org/wiki/Planet_Nine",
          "domain": "en.wikipedia.org",
          "title": "Planet Nine - Wikipedia",
          "snippet": "Tools Actions Read Edit View history General What links here Related changes Upload file Permanent link Page information Cite this page Get shortened URL Switch to legacy parser Print/export Download as PDF Printable version In other projects Wikimedia Commons Wikiversity Wikidata item Appearance Featured article From ",
          "stance": "neutral",
          "credibility": 0.81
        }
      },
      {
        "type": "source",
        "claimId": "c2",
        "source": {
          "id": "c2-s4",
          "url": "https://science.nasa.gov/solar-system/planet-x",
          "domain": "science.nasa.gov",
          "title": "Hypothetical Planet X",
          "snippet": "Pluto was considered the ninth major planet in our solar system until the definition of “planet” was changed by the International Astronomical Union (IAU) in 2016. This new definition reclassified Pluto as a dwarf planet. Even before the IAU action, back when it was discovered, it was thought that Pluto was as massive ",
          "stance": "neutral",
          "credibility": 1
        }
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "arguing"
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-source_quality",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "source quality",
          "position": "Pluto is no longer classified as a planet; it was reclassified as a dwarf planet, so it is not the ninth planet in the solar system.",
          "sourceIds": [
            "c2-s2",
            "c2-s4"
          ],
          "strength": 0.9
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-temporal",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "temporal staleness",
          "position": "Pluto is no longer classified as the ninth planet; it was redefined as a dwarf planet in 2016, making the claim outdated.",
          "sourceIds": [
            "c2-s2"
          ],
          "strength": 0.9
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-entity",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "entity conflation",
          "position": "No entity conflation is present; the claim incorrectly states Pluto’s current status rather than confusing it with another object such as the hypothetical Planet Nine",
          "sourceIds": [
            "c2-s2",
            "c2-s4"
          ],
          "strength": 0.2
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-logic",
          "claimId": "c2",
          "role": "prosecutor",
          "lens": "logical leap",
          "position": "The claim illogically leaps from a historical designation to a present absolute, ignoring the explicit evidence that Pluto was reclassified as a dwarf planet under an updated definition.",
          "sourceIds": [
            "c2-s2",
            "c2-s4"
          ],
          "strength": 0.9
        }
      },
      {
        "type": "argument",
        "claimId": "c2",
        "argument": {
          "id": "c2-defense",
          "claimId": "c2",
          "role": "defense",
          "lens": "strongest defense",
          "position": "Pluto was historically designated as the ninth planet and its planetary status remains debated by experts, supporting the claim's historical accuracy despite its official reclassification as a dwarf planet.",
          "sourceIds": [
            "c2-s1",
            "c2-s2",
            "c2-s4"
          ],
          "strength": 0.2
        }
      },
      {
        "type": "claim_status",
        "claimId": "c2",
        "status": "judging"
      },
      {
        "type": "verdict",
        "claimId": "c2",
        "verdict": "refuted",
        "confidence": 0.99,
        "failureType": "stale_fact",
        "reasoning": "NASA states that Pluto was once considered the ninth planet but is now classified as a dwarf planet in the Kuiper Belt. The claim reflects Pluto’s historical designation, not its current official classification.",
        "disagreement": 0.61
      },
      {
        "type": "claim_status",
        "claimId": "c3",
        "status": "retrieving"
      },
      {
        "type": "source",
        "claimId": "c3",
        "source": {
          "id": "c3-s1",
          "url": "https://www.westeamahead.org/blog/do-we-only-use-10-of-our-brain",
          "domain": "westeamahead.org",
          "title": "MythBuster: Do We Only Use 10% of Our Brain",
          "snippet": "### Myth: Humans Only Use 10% of Their Brains The myth that humans only use 10% of their brains is FALSE. Movies like Lucy and Limitless fuel this idea. These stories suggest that unlocking more of our brain could grant superhuman abilities, such as telekinesis or infinite memory. Science, however, proves otherwise. Ne",
          "stance": "neutral",
          "credibility": 0.85
        }
      },
      {
        "type": "source",
        "claimId": "c3",
        "source": {
          "id": "c3-s2",
          "url": "https://www.psychologytoday.com/us/blog/common-sense-science/202505/beyond-the-myth-that-we-use-only-10-percent-of-our-brains/amp",
          "domain": "psychologytoday.com",
          "title": "Beyond the Myth That We Use Only 10 Percent of Our Brains | Psychology Today",
          "snippet": "One of the most enduring myths in pop psychology is that humans use only 10 percent of their brains. This notion, repeated in movies, motivational speeches, and even some classrooms, implies that a vast cognitive potential remains untapped. However, this idea is scientifically inaccurate and undermines our understandin",
          "stance": "neutral",
          "credibility": 0.84
        }
      },
      {
        "type": "source",
        "claimId": "c3",
        "source": {
          "id": "c3-s3",
          "url": "https://www.britannica.com/story/do-we-really-use-only-10-percent-of-our-brain",
          "domain": "britannica.com",
          "title": "Do We Really Use Only 10 Percent of Our Brain? | Britannica",
          "snippet": "Encyclopedia Britannica Encyclopedia Britannica Brain illustration Britannica AI Icon Our editors will review what you’ve submitted and determine whether to revise the article. Brain illustration # Do We Really Use Only 10 Percent of Our Brain? Britannica AI Icon It’s one of Hollywood’s favorite bits of pseudoscience: ",
          "stance": "neutral",
          "credibility": 0.84
        }
      },
      {
        "type": "source",
        "claimId": "c3",
        "source": {
          "id": "c3-s4",
          "url": "https://uamshealth.com/medical-myths/do-people-only-use-10-percent-of-our-brains",
          "domain": "uamshealth.com",
          "title": "Do People Only Use 10 Percent of our Brains? | UAMS Health",
          "snippet": "UAMS Health Logo # Do People Only Use 10 Percent of our Brains? It’s appealing to think we could be smarter if only we applied more of our brain power. Unfortunately, the idea that people only use 10% of our brains and could use more is not true. This persistent myth may have originated as early as 1908 when William Ja",
          "stance": "neutral",
          "credibility": 0.83
        }
      },
      {
        "type": "claim_status",
        "claimId": "c3",
        "status": "arguing"
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-source_quality",
          "claimId": "c3",
          "role": "prosecutor",
          "lens": "source quality",
          "position": "All provided sources directly address the claim and are reputable fact‑checking or educational sites; there is no evidence of mis‑attributed, fabricated, or irrelevant citations.",
          "sourceIds": [
            "c3-s1",
            "c3-s2",
            "c3-s3",
            "c3-s4"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-temporal",
          "claimId": "c3",
          "role": "prosecutor",
          "lens": "temporal staleness",
          "position": "The claim asserts a present-tense reality, but the evidence traces the origin of this idea to 1908. Because the claim lacks any temporal framing to contextualize it as a historical belief, it improperly presents a century-old notion as a current fact.",
          "sourceIds": [
            "c3-s4"
          ],
          "strength": 0.85
        }
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-entity",
          "claimId": "c3",
          "role": "prosecutor",
          "lens": "entity conflation",
          "position": "No entity conflation is evident; the claim does not merge or misattribute different studies, authors, or institutions.",
          "sourceIds": [
            "c3-s1"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-logic",
          "claimId": "c3",
          "role": "prosecutor",
          "lens": "logical leap",
          "position": "The claim makes an absolute (\"only 10%\") inference without supporting evidence; neuro‑science sources show that brain activity is distributed across virtually the entire organ, disproving the 10% figure",
          "sourceIds": [
            "c3-s1"
          ],
          "strength": 0.8
        }
      },
      {
        "type": "argument",
        "claimId": "c3",
        "argument": {
          "id": "c3-defense",
          "claimId": "c3",
          "role": "defense",
          "lens": "strongest defense",
          "position": "The claim that humans only use 10% of their brains is largely a myth; the sources explain that virtually all parts of the brain have known functions and are active, so any literal 10% usage interpretation lacks scientific support.",
          "sourceIds": [
            "c3-s1"
          ],
          "strength": 0.1
        }
      },
      {
        "type": "claim_status",
        "claimId": "c3",
        "status": "judging"
      },
      {
        "type": "verdict",
        "claimId": "c3",
        "verdict": "refuted",
        "confidence": 0.99,
        "failureType": "common_misconception",
        "reasoning": "The evidence consistently identifies the 10% claim as a popular myth rather than a scientific fact. UAMS Health directly states that people do not use only 10% of their brains, while Britannica and the other sources independently agree. The reference to 1908 concerns the myth’s possible origin, not evidence that it was ever true.",
        "disagreement": 0.73
      },
      {
        "type": "done",
        "trustScore": 34
      }
    ]
  }
];

export function fixtureById(id: string): Fixture | undefined {
  return FIXTURES.find((f) => f.id === id);
}

/**
 * Replay a recorded trial with lifelike pacing, so the interface animates the
 * same way it does on a live run. Returns a cancel function.
 */
export function replayFixture(
  fixture: Fixture,
  onEvent: (e: StreamEvent) => void,
  speed = 1,
): () => void {
  let cancelled = false;

  (async () => {
    for (const e of fixture.events) {
      const pause =
        e.type === "claims"
          ? 700
          : e.type === "claim_status"
            ? 420
            : e.type === "verdict"
              ? 900
              : 300 + Math.random() * 340;
      await new Promise((r) => setTimeout(r, pause / speed));
      if (cancelled) return;
      onEvent(e);
    }
  })();

  return () => {
    cancelled = true;
  };
}
